# Generated by Django 6.0.6 on 2026-07-07 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в формате +49123456789 (от 8 до 15 цифр)', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
    ]
