# Generated by Django 6.0.6 on 2026-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingview',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
