# Generated by Django 6.0.6 on 2026-07-07 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('listings', '0004_listing_deleted_at_listing_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gt', models.F('date_from'))), name='booking_date_to_after_date_from'),
        ),
    ]
