# Generated by Django 6.0.6 on 2026-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booking_date_to_after_date_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant_notified',
            field=models.BooleanField(default=True),
        ),
    ]
