# Generated by Django 6.0.6 on 2026-07-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='listing',
        ),
    ]
