# Generated by Django 6.0.6 on 2026-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='landlord_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
